// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feeds.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (id, created_at, updated_at, name, url, user_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, name, url, user_id
`

type CreateFeedParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Url       string
	UserID    uuid.UUID
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Url,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}

const createFeedFollow = `-- name: CreateFeedFollow :one
WITH feed_follow_insert AS (
	INSERT INTO feed_follows (id, created_at, updated_at, user_id, feed_id)
	VALUES (
		$1,
		$2,
		$3,
		$4,
		$5
	)
returning id, created_at, updated_at, user_id, feed_id 
)

select
	feed_follow_insert.id,
	feed_follow_insert.created_at,
	feed_follow_insert.updated_at,
	users.name as user,
	feeds.name as feed
from 
	feed_follow_insert
inner join users
on
	feed_follow_insert.user_id = users.id
inner join feeds
on 
	feed_follow_insert.feed_id = feeds.id
`

type CreateFeedFollowParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

type CreateFeedFollowRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	User      string
	Feed      string
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i CreateFeedFollowRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.User,
		&i.Feed,
	)
	return i, err
}

const feedByURL = `-- name: FeedByURL :one
SELECT
	id, created_at, updated_at, name, url, user_id
FROM
	feeds
where
	url = $1
`

func (q *Queries) FeedByURL(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, feedByURL, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}

const feedList = `-- name: FeedList :many
SELECT
	feeds.id,
	feeds.name as feed,
	url,
	feeds.created_at,
	feeds.updated_at,
	users.name as user
FROM
	feeds
INNER JOIN
	users
ON
	feeds.user_id = users.id
`

type FeedListRow struct {
	ID        uuid.UUID
	Feed      string
	Url       string
	CreatedAt time.Time
	UpdatedAt time.Time
	User      string
}

func (q *Queries) FeedList(ctx context.Context) ([]FeedListRow, error) {
	rows, err := q.db.QueryContext(ctx, feedList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedListRow
	for rows.Next() {
		var i FeedListRow
		if err := rows.Scan(
			&i.ID,
			&i.Feed,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.User,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedFollowsForUser = `-- name: GetFeedFollowsForUser :many
select
	feeds.name as feed,
	users.name as user
from feed_follows
inner join 
	feeds
on
	feeds.id = feed_follows.feed_id
inner join
	users
on
	users.id = feed_follows.user_id
where
	feed_follows.user_id = $1
`

type GetFeedFollowsForUserRow struct {
	Feed string
	User string
}

func (q *Queries) GetFeedFollowsForUser(ctx context.Context, userID uuid.UUID) ([]GetFeedFollowsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedFollowsForUserRow
	for rows.Next() {
		var i GetFeedFollowsForUserRow
		if err := rows.Scan(&i.Feed, &i.User); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
